# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Categorize deck archetype stats

Resources:
    CategorizeDeckQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: categorize-decks-queue
            VisibilityTimeout: 601
    CategorizeDeckSqsQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Id: CategorizeDeckQueuePolicy
                Statement:
                    - Sid: Allow-SNS-SendMessage
                      Effect: Allow
                      Principal:
                          AWS: '*'
                      Action:
                          - sqs:SendMessage
                      Resource: !GetAtt CategorizeDeckQueue.Arn
                      Condition:
                          ArnEquals:
                              aws:SourceArn: arn:aws:sns:us-west-2:478062583808:ranked-review-published
            Queues:
                - !Ref CategorizeDeckQueue
    SnsSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Protocol: SQS
            Endpoint: !GetAtt CategorizeDeckQueue.Arn
            TopicArn: arn:aws:sns:us-west-2:478062583808:ranked-review-published

    CategorizeDeckFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: categorize-deck.default
            Runtime: nodejs10.x
            Timeout: 40
            CodeUri: ./dist/categorize-deck
            MemorySize: 256
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: trigger-categorize-deck
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt CategorizeDeckQueue.Arn
